services:
  database:
    container_name: "postgres-dev"
    image: "postgres:17.6"
    restart: always
    env_file:
      - ../../.env.development
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U local_user -d local_db"]
      interval: 3s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  api:
    container_name: "dev-api"
    image: oliveirawladimir/hipersenna-api:2.0.1
    env_file:
      - ../../.env.development
    environment:
      - POSTGRES_HOST=database
    command: sh -c "npx prisma migrate dev && npx prisma db seed && npm run dev"
    ports:
      - 3333:3333
    depends_on:
      database:
        condition: service_healthy

  # saas:
  #   container_name: "saas"
  #   image: oliveirawladimir/hipersenna-saas:2.2.1
  #   env_file:
  #     - ../../.env.production
  #   ports:
  #     - 3000:3000
