services:
  database:
    container_name: "postgres-dev"
    image: "postgres:17.6"
    restart: always
    shm_size: 128mb
    env_file:
      - ../../.env.docker
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U local_user -d local_db"]
      interval: 3s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432

  migrations:
    container_name: prisma_migrations
    image: oliveirawladimir/hipersenna-api:1.4.2
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - ../../.env.docker
    entrypoint: >
      sh -c "
        echo '⌛ Executando migrations prisma...' &&
        npx prisma generate &&
        npx prisma migrate dev --name migrations-dev &&
        echo '✅ Migrations concluídas'
      "

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  api:
    container_name: "hs_dev_api"
    image: oliveirawladimir/hipersenna-api:1.4.2
    depends_on:
      migrations:
        condition: service_completed_successfully
    env_file:
      - ../../.env.docker
    ports:
      - 3333:3333
# volumes:
#   hipers_pg_data:
