services:
  database:
    container_name: "postgres_dev"
    image: "postgres:17.6"
    restart: always
    shm_size: 128mb
    env_file:
      - ../../.env.docker
    ports:
      - 5432:5432
    volumes:
      - hipers_pg_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  api:
    container_name: "hs_dev_api"
    image: oliveirawladimir/hipersenna-api:1.1
    env_file:
      - ../../.env.docker
    ports:
      - 3333:3333

volumes:
  hipers_pg_data:
