services:
  database:
    container_name: "postgres-dev"
    image: "postgres:17.6"
    restart: always
    shm_size: 128mb
    env_file:
      - ../../.env.docker
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  api:
    container_name: "dev-api"
    image: oliveirawladimir/hipersenna-api:1.4.5
    env_file:
      - ../../.env.docker
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U local_user -d local_db"]
      interval: 3s
      timeout: 5s
      retries: 5
    entrypoint: >
      sh -c "
        echo '⌛ Executando migrations prisma...' &&
        npx prisma generate &&
        npx prisma migrate dev --name migrations-dev &&
        npm run init:db &&
        echo '✅ Migrations concluídas' &&
        npm run dev
      "
    ports:
      - 3333:3333
